name: example
description: Example of exponential_back_off usage
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  simple_exponential_backoff:
    path: ../
  http: any