name: simple_exponential_backoff
description: A package that provides an exponential backoff algorithm.
version: 0.1.0+1
homepage: https://github.com/felipeddev/exponential_backoff

dependencies:
  async: ^2.11.0
  simple_either: ^1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1